"""
04_export.py — TFLite INT8 model -> C array + normalization header + test vectors

Generates three C files:
  app/src/ml/model_data.cc         — model as alignas(8) C array
  app/src/dsp/mel_filterbank_weights.h  — mel filterbank (64x257 float32)
  app/src/dsp/normalization_params.h   — training set mean + std
  app/src/ml/test_vectors.h        — 10 test spectrograms + expected labels

Also generates generate_filterbank.py output inline.

Usage:
    python ml/04_export.py [--data-dir ml/data]
"""

import os
import sys
import argparse
import numpy as np
from pathlib import Path

import librosa


# DSP params (must match mel_spec.h)
SR_TARGET  = 4000
N_FFT      = 512
N_MELS     = 64
F_MIN      = 25
F_MAX      = 2000
FFT_BINS   = N_FFT // 2 + 1  # 257


def generate_filterbank_header(out_path: Path):
    """Compute mel filterbank weights and write to C header."""
    fb = librosa.filters.mel(sr=SR_TARGET, n_fft=N_FFT, n_mels=N_MELS,
                              fmin=F_MIN, fmax=F_MAX)
    # fb shape: (N_MELS, FFT_BINS) = (64, 257)
    assert fb.shape == (N_MELS, FFT_BINS), f"Unexpected filterbank shape: {fb.shape}"

    lines = [
        "/*",
        " * mel_filterbank_weights.h — AUTO-GENERATED by ml/04_export.py",
        f" * librosa.filters.mel(sr={SR_TARGET}, n_fft={N_FFT}, "
        f"n_mels={N_MELS}, fmin={F_MIN}, fmax={F_MAX})",
        f" * Shape: [{N_MELS}][{FFT_BINS}] float32",
        " */",
        "",
        "#ifndef MEL_FILTERBANK_WEIGHTS_H",
        "#define MEL_FILTERBANK_WEIGHTS_H",
        "",
        f"#define MEL_FILTERBANK_ROWS  {N_MELS}",
        f"#define MEL_FILTERBANK_COLS  {FFT_BINS}",
        "",
        f"static const float mel_filterbank[{N_MELS}][{FFT_BINS}] = {{",
    ]

    for m in range(N_MELS):
        row_vals = ", ".join(f"{v:.8e}f" for v in fb[m])
        lines.append(f"    /* Row {m:2d} */ {{ {row_vals} }},")

    lines += ["};", "", "#endif /* MEL_FILTERBANK_WEIGHTS_H */", ""]

    out_path.write_text("\n".join(lines))
    print(f"  Filterbank weights -> {out_path}  ({N_MELS}x{FFT_BINS})")


def generate_normalization_header(norm_params_path: Path, out_path: Path):
    """Write training set mean/std to C header."""
    params = np.load(norm_params_path)
    mean, std = float(params[0]), float(params[1])

    content = f"""\
/*
 * normalization_params.h — AUTO-GENERATED by ml/04_export.py
 * Training set mean and standard deviation for per-spectrogram normalization.
 * Applied in mel_spec.c after log10 compression.
 */

#ifndef NORMALIZATION_PARAMS_H
#define NORMALIZATION_PARAMS_H

#define NORM_MEAN  {mean:.8e}f
#define NORM_STD   {std:.8e}f

#endif /* NORMALIZATION_PARAMS_H */
"""
    out_path.write_text(content)
    print(f"  Normalization params -> {out_path}  (mean={mean:.4f}, std={std:.4f})")


def generate_model_cc(tflite_path: Path, out_path: Path):
    """Convert .tflite binary to C array using Python (replaces xxd)."""
    model_bytes = tflite_path.read_bytes()
    n = len(model_bytes)

    lines = [
        "/*",
        " * model_data.cc — AUTO-GENERATED by ml/04_export.py",
        f" * Source: {tflite_path.name}  ({n} bytes)",
        " * Do not edit manually — regenerate with: python ml/04_export.py",
        " */",
        "",
        '#include "model_data.h"',
        "",
        f"alignas(8) const unsigned char g_model_data[] = {{",
    ]

    hex_vals = [f"0x{b:02x}" for b in model_bytes]
    # 16 bytes per line
    for i in range(0, len(hex_vals), 16):
        chunk = ", ".join(hex_vals[i:i+16])
        lines.append(f"    {chunk},")

    lines += [
        "};",
        "",
        f"const unsigned int g_model_data_len = {n}U;",
        "",
    ]

    out_path.write_text("\n".join(lines))
    print(f"  Model C array -> {out_path}  ({n} bytes = {n/1024:.1f} KB)")


def generate_test_vectors(data_root: Path, n_per_class: int, out_path: Path,
                           norm_mean: float, norm_std: float):
    """
    Load N spectrograms per class from test set, normalize, write to C header.
    Used by the on-device validation script and AudioCapture stub.
    """
    class_names  = ["absent", "present", "unknown"]
    class_labels = [0, 1, 2]

    all_specs  = []
    all_labels = []

    test_dir = data_root / "test"
    for class_name, label in zip(class_names, class_labels):
        class_dir = test_dir / class_name
        if not class_dir.exists():
            print(f"  WARNING: test/{class_name}/ not found — skipping")
            continue
        files = sorted(class_dir.glob("*.npy"))[:n_per_class]
        for f in files:
            spec = np.load(f).astype(np.float32)
            # Apply dataset normalization
            spec = (spec - norm_mean) / (norm_std + 1e-8)
            all_specs.append(spec)
            all_labels.append(label)

    n_vectors = len(all_specs)
    if n_vectors == 0:
        print("  WARNING: No test vectors found — test_vectors.h will be empty")
        return

    print(f"  Generating {n_vectors} test vectors ({n_per_class} per class)...")

    lines = [
        "/*",
        " * test_vectors.h — AUTO-GENERATED by ml/04_export.py",
        f" * {n_vectors} normalized 64x64 log-mel spectrograms for on-device validation",
        " */",
        "",
        "#ifndef TEST_VECTORS_H",
        "#define TEST_VECTORS_H",
        "",
        f"#define TEST_VECTOR_COUNT   {n_vectors}",
        "#define TEST_VECTOR_SAMPLES  (64 * 64)",
        "",
        "static const char *test_vector_class_names[] = {",
        '    "Absent", "Present", "Unknown"',
        "};",
        "",
        f"static const int test_vector_labels[{n_vectors}] = {{",
        "    " + ", ".join(str(l) for l in all_labels),
        "};",
        "",
    ]

    # Write each spectrogram as a float array
    for i, spec in enumerate(all_specs):
        flat  = spec.flatten()
        label = all_labels[i]
        lines.append(f"/* Vector {i}: class={class_names[label]} */")
        lines.append(f"static const float test_vector_{i}[TEST_VECTOR_SAMPLES] = {{")
        hex_vals = [f"{v:.6e}f" for v in flat]
        for j in range(0, len(hex_vals), 8):
            lines.append("    " + ", ".join(hex_vals[j:j+8]) + ",")
        lines.append("};")
        lines.append("")

    # Master pointer array
    lines.append(f"static const float *test_vectors[{n_vectors}] = {{")
    for i in range(n_vectors):
        lines.append(f"    test_vector_{i},")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* TEST_VECTORS_H */")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"  Test vectors -> {out_path}  ({n_vectors} vectors)")


def main():
    parser = argparse.ArgumentParser(description="Export model to C arrays")
    parser.add_argument("--data-dir",     default="ml/data_circor")
    parser.add_argument("--n-per-class",  type=int, default=3,
                        help="Test vectors per class (10 total for 4 classes with overlap)")
    parser.add_argument("--arch", choices=["resnet10", "resnet18"], default="resnet10",
                        help="Which trained model variant to export.")
    args = parser.parse_args()

    data_root   = Path(args.data_dir)
    processed   = data_root / "processed"
    model_dir   = Path("ml/models")
    app_dsp_dir = Path("app/src/dsp")
    app_ml_dir  = Path("app/src/ml")

    tflite_path    = model_dir / f"{args.arch}_int8.tflite"
    norm_path      = data_root / "normalization_params.npy"

    if not tflite_path.exists():
        print(f"ERROR: {tflite_path} not found. Run ml/03_quantize.py first.")
        sys.exit(1)

    # ── Mel filterbank ────────────────────────────────────────────────────────
    print("=== Generating mel filterbank weights ===")
    filterbank_path = app_dsp_dir / "mel_filterbank_weights.h"
    if filterbank_path.exists():
        print(f"  Keeping existing filterbank weights -> {filterbank_path}")
    else:
        generate_filterbank_header(filterbank_path)

    # ── Normalization params ──────────────────────────────────────────────────
    if norm_path.exists():
        print("\n=== Generating normalization params ===")
        generate_normalization_header(norm_path, app_dsp_dir / "normalization_params.h")
        norm_params = np.load(norm_path)
        norm_mean, norm_std = float(norm_params[0]), float(norm_params[1])
    else:
        print(f"\nWARNING: {norm_path} not found — skipping normalization header")
        norm_mean, norm_std = 0.0, 1.0

    # ── Model C array ─────────────────────────────────────────────────────────
    print("\n=== Converting model to C array ===")
    generate_model_cc(tflite_path, app_ml_dir / "model_data.cc")

    # ── Test vectors ──────────────────────────────────────────────────────────
    if processed.exists():
        print("\n=== Generating test vectors ===")
        generate_test_vectors(processed, args.n_per_class,
                              app_ml_dir / "test_vectors.h",
                              norm_mean, norm_std)
    else:
        print(f"\nWARNING: {processed} not found — skipping test vectors")

    print("\n=== Export complete ===")
    print("  Build the firmware:  cd app && west build -b nucleo_u575zi_q .")
    print("  Validate on-device:  python ml/05_validate_on_device.py")


if __name__ == "__main__":
    main()
