"""
05_validate_on_device.py -- On-device inference validation via UART

Sends test spectrogram vectors to the STM32U575 and compares on-device
results against the Python TFLite reference interpreter.

Protocol (STM32 runs validate_thread from app/src/ml/validate.c):
  Host -> STM32 : 'T' (0x54) + uint16 index (little-endian, 3 bytes total)
  STM32 -> Host : 0xA5 (magic) + class_id (uint8) + confidence (uint8)

The 0xA5 magic byte is never in Zephyr LOG text, so we can find the
response unambiguously even though LOG output shares the same UART.

Usage:
    python ml/05_validate_on_device.py --port COM6 [--baud 115200]
    python ml/05_validate_on_device.py --port /dev/ttyACM0

Requirements: pyserial, tensorflow (pip install pyserial tensorflow)
"""

import argparse
import struct
import sys
import time
import numpy as np

try:
    import serial
except ImportError:
    print("ERROR: pyserial not installed.  Run: pip install pyserial")
    sys.exit(1)

try:
    import tensorflow as tf
except ImportError:
    print("ERROR: tensorflow not installed.  Run: pip install tensorflow")
    sys.exit(1)

from pathlib import Path


CLASS_NAMES = ["Absent", "Present", "Unknown"]
RESPONSE_MAGIC = 0xA5
UNKNOWN_CLASS_ID = 2
UNKNOWN_MIN_PROB = 0.10
UNKNOWN_TOP_MAX = 0.60
UNKNOWN_MARGIN_MAX = 0.41


# ---------------------------------------------------------------------------
# Python TFLite reference
# ---------------------------------------------------------------------------

def run_tflite_reference(interp, inp_det, out_det, spec: np.ndarray):
    """Run one inference on the host TFLite interpreter (INT8 model)."""
    # Model expects (1, 64, 64, 1)
    inp = spec[np.newaxis, :, :, np.newaxis].astype(np.float32)

    if inp_det["dtype"] == np.int8:
        scale, zero_pt = inp_det["quantization"]
        inp = (inp / scale + zero_pt).clip(-128, 127).astype(np.int8)

    interp.set_tensor(inp_det["index"], inp)
    interp.invoke()
    out = interp.get_tensor(out_det["index"])

    if out_det["dtype"] == np.int8:
        scale, zero_pt = out_det["quantization"]
        out = (out.astype(np.float32) - zero_pt) * scale

    probs = out.reshape(-1)
    class_id = int(np.argmax(probs))
    confidence = float(probs[class_id])

    sorted_probs = np.sort(probs)
    top = float(sorted_probs[-1])
    second = float(sorted_probs[-2]) if len(sorted_probs) > 1 else 0.0
    unknown = float(probs[UNKNOWN_CLASS_ID]) if len(probs) > UNKNOWN_CLASS_ID else 0.0

    if (len(probs) > UNKNOWN_CLASS_ID and
            class_id != UNKNOWN_CLASS_ID and
            unknown >= UNKNOWN_MIN_PROB and
            (top <= UNKNOWN_TOP_MAX or (top - second) <= UNKNOWN_MARGIN_MAX)):
        class_id = UNKNOWN_CLASS_ID
        confidence = unknown

    return class_id, confidence


# ---------------------------------------------------------------------------
# Device communication
# ---------------------------------------------------------------------------

def recv_response(ser: serial.Serial, timeout: float = 3.0) -> tuple[int, int] | None:
    """
    Read bytes until the 0xA5 magic appears, then return (class_id, confidence).
    Returns None on timeout.
    """
    deadline = time.time() + timeout
    while time.time() < deadline:
        b = ser.read(1)
        if not b:
            continue
        if b[0] == RESPONSE_MAGIC:
            rest = ser.read(2)
            if len(rest) == 2:
                return rest[0], rest[1]
    return None


# ---------------------------------------------------------------------------
# Main validation loop
# ---------------------------------------------------------------------------

def load_test_vectors(data_root: Path, n_per_class: int,
                      norm_mean: float, norm_std: float):
    """Load and normalise test spectrograms — same order as test_vectors.h."""
    class_dirs  = ["absent", "present", "unknown"]
    class_labels = [0, 1, 2]
    vectors = []

    test_dir = data_root / "test"
    for dir_name, label in zip(class_dirs, class_labels):
        class_dir = test_dir / dir_name
        if not class_dir.exists():
            print(f"  WARNING: {class_dir} not found -- skipping class {dir_name}")
            continue
        files = sorted(class_dir.glob("*.npy"))[:n_per_class]
        for f in files:
            spec = np.load(f).astype(np.float32)
            spec = (spec - norm_mean) / (norm_std + 1e-8)   # same as test_vectors.h
            vectors.append((spec, label, dir_name))

    return vectors


def validate_on_device(port: str, baud: int,
                       tflite_path: Path, data_root: Path,
                       n_per_class: int):

    # Load normalization params (generated by ml/03_quantize.py)
    norm_path = data_root.parent / "normalization_params.npy"
    if norm_path.exists():
        params = np.load(norm_path)
        norm_mean, norm_std = float(params[0]), float(params[1])
        print(f"Normalization: mean={norm_mean:.4f}  std={norm_std:.4f}")
    else:
        # Fallback to hardcoded values from normalization_params.h
        norm_mean, norm_std = -5.84965515, 3.58822751
        print(f"Normalization: using hardcoded fallback "
              f"(mean={norm_mean:.4f}  std={norm_std:.4f})")

    vectors = load_test_vectors(data_root, n_per_class, norm_mean, norm_std)
    if not vectors:
        print("ERROR: No test vectors found.  Run ml/01_preprocess.py first.")
        return

    print(f"Loaded {len(vectors)} test vectors ({n_per_class} per class)")

    # Build TFLite reference interpreter (reused across all vectors)
    ref_interp = tf.lite.Interpreter(model_path=str(tflite_path))
    ref_interp.allocate_tensors()
    inp_det = ref_interp.get_input_details()[0]
    out_det = ref_interp.get_output_details()[0]

    # Open serial port
    try:
        ser = serial.Serial(port, baud, timeout=0.1)
        time.sleep(0.2)
        ser.reset_input_buffer()
        print(f"Connected to {port} at {baud} baud\n")
    except serial.SerialException as e:
        print(f"ERROR opening {port}: {e}")
        return

    correct_vs_true  = 0
    correct_vs_ref   = 0
    total = len(vectors)

    print(f"{'#':>3}  {'True':<16} {'Reference':<20} {'Device':<20} {'Match'}")
    print("-" * 72)

    try:
        for i, (spec, true_label, dir_name) in enumerate(vectors):
            # Python reference
            ref_class, ref_conf = run_tflite_reference(
                ref_interp, inp_det, out_det, spec)

            # Send command to device: 'T' + u16 index
            ser.write(b'T' + struct.pack('<H', i))
            ser.flush()

            result = recv_response(ser, timeout=3.0)

            if result is None:
                print(f"{i:>3}  {CLASS_NAMES[true_label]:<16} "
                      f"{CLASS_NAMES[ref_class]:<14}({ref_conf*100:.0f}%)  "
                      f"{'TIMEOUT':<20} FAIL")
                continue

            dev_class, dev_conf = result

            if dev_class == true_label:
                correct_vs_true += 1
            vs_ref = "OK" if dev_class == ref_class else "DIFF"
            if dev_class == ref_class:
                correct_vs_ref += 1

            print(f"{i:>3}  {CLASS_NAMES[true_label]:<16} "
                  f"{CLASS_NAMES[ref_class]:<14}({ref_conf*100:.0f}%)  "
                  f"{CLASS_NAMES[dev_class] if dev_class < len(CLASS_NAMES) else 'INVALID':<14}"
                  f"({dev_conf}%)  {vs_ref}")

    finally:
        ser.close()

    print("-" * 72)
    acc_true = correct_vs_true / total * 100
    acc_ref  = correct_vs_ref  / total * 100
    print(f"\nOn-device accuracy vs true labels : {correct_vs_true}/{total} = {acc_true:.1f}%")
    print(f"On-device vs Python reference     : {correct_vs_ref}/{total} = {acc_ref:.1f}%")

    if acc_ref < 95.0:
        print("\nWARNING: >5% divergence between device and reference.")
        print("  Possible causes: normalization mismatch, arena overflow, "
              "quantization bug.")
    else:
        print("\nPASS -- device matches Python TFLite reference within tolerance.")


# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="On-device UART inference validation for Digital Stethoscope")
    parser.add_argument("--port",         default="COM6",
                        help="Serial port  (e.g. COM6 or /dev/ttyACM0)")
    parser.add_argument("--baud",         type=int, default=115200)
    parser.add_argument("--data-dir",     default="ml/data_circor",
                        help="Root of processed data directory")
    parser.add_argument("--model",        default="ml/models/resnet10_int8.tflite",
                        help="Path to INT8 .tflite model")
    parser.add_argument("--n-per-class",  type=int, default=3,
                        help="Test vectors per class (must match test_vectors.h)")
    args = parser.parse_args()

    tflite_path = Path(args.model)
    data_root   = Path(args.data_dir) / "processed"

    if not tflite_path.exists():
        print(f"ERROR: {tflite_path} not found.  Run ml/03_quantize.py first.")
        sys.exit(1)
    if not data_root.exists():
        print(f"ERROR: {data_root} not found.  Run ml/01_preprocess.py first.")
        sys.exit(1)

    validate_on_device(args.port, args.baud, tflite_path, data_root,
                       args.n_per_class)


if __name__ == "__main__":
    main()
