"""
generate_filterbank.py — Generate mel filterbank C header standalone

Used when you want to regenerate just the filterbank weights without
running the full export pipeline.

Usage:
    python ml/generate_filterbank.py
"""

import numpy as np
import librosa
from pathlib import Path

SR_TARGET = 4000
N_FFT     = 512
N_MELS    = 64
F_MIN     = 25
F_MAX     = 2000
FFT_BINS  = N_FFT // 2 + 1  # 257

OUT_PATH  = Path("app/src/dsp/mel_filterbank_weights.h")

fb = librosa.filters.mel(sr=SR_TARGET, n_fft=N_FFT, n_mels=N_MELS,
                          fmin=F_MIN, fmax=F_MAX)
print(f"Filterbank shape: {fb.shape}  min={fb.min():.4f}  max={fb.max():.4f}")

lines = [
    "/*",
    " * mel_filterbank_weights.h — AUTO-GENERATED by ml/generate_filterbank.py",
    f" * librosa.filters.mel(sr={SR_TARGET}, n_fft={N_FFT}, "
    f"n_mels={N_MELS}, fmin={F_MIN}, fmax={F_MAX})",
    f" * Shape: [{N_MELS}][{FFT_BINS}] float32",
    " */",
    "",
    "#ifndef MEL_FILTERBANK_WEIGHTS_H",
    "#define MEL_FILTERBANK_WEIGHTS_H",
    "",
    f"#define MEL_FILTERBANK_ROWS  {N_MELS}",
    f"#define MEL_FILTERBANK_COLS  {FFT_BINS}",
    "",
    f"static const float mel_filterbank[{N_MELS}][{FFT_BINS}] = {{",
]

for m in range(N_MELS):
    row_vals = ", ".join(f"{v:.8e}f" for v in fb[m])
    lines.append(f"    /* Row {m:2d} */ {{ {row_vals} }},")

lines += ["};", "", "#endif /* MEL_FILTERBANK_WEIGHTS_H */", ""]

OUT_PATH.write_text("\n".join(lines))
print(f"Written: {OUT_PATH}")
