/*
 * normalization_params.h — AUTO-GENERATED by ml/04_export.py
 * Training set mean and standard deviation for per-spectrogram normalization.
 * Applied in mel_spec.c after log10 compression.
 */

#ifndef NORMALIZATION_PARAMS_H
#define NORMALIZATION_PARAMS_H

#define NORM_MEAN  -3.02136254e+00f
#define NORM_STD   1.56939304e+00f

#endif /* NORMALIZATION_PARAMS_H */
