#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

/* Exported from model_data.cc — generated by ml/04_export.py via xxd */
extern const unsigned char g_model_data[];
extern const unsigned int  g_model_data_len;

#endif /* MODEL_DATA_H */
